CREATE TABLE IF NOT EXISTS IP_POOL
(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    ip   VARCHAR(250) NOT NULL,
    port INT          NOT NULL
);

CREATE TABLE IF NOT EXISTS LV_SKU
(
    id    INT AUTO_INCREMENT PRIMARY KEY,
    sku   VARCHAR(50) NOT NULL,
    url   VARCHAR(500),
    title VARCHAR(100),
);